### ISSUE TITLE
New version available 1.11.1

### ISSUE THREAD

**Issue by alculete** [jssotomdz/jmp-snap#9]

**Comment by cclecle** [comment]
Please can you udpdate to this version ?
The version 1.11.0 have a big bug preventing to use subdirectories ... (aka: https://domain/jellyfin ) , which is fixed in 1.11.1 :).

**Comment by jssotomdz** [comment]
Hi! Sorry for the delay, I'm an unofficial maintainer and I do this in my free time. Normally I like to test the build before pushing to the distribution channels.
If you want to help newer versions go out quicker, you can help opening a pull request with the following change (https://github.com/jssotomdz/jmp-snap/commit/b2d5c55dd4048e01a802186e52c2b5a90b9b4632). Basically just changing the version tag. I have a CI test to make sure it builds and after approval, you can test it in the edge channel.
Thanks for using the Jellyfin snap!
